"""Catálogo interno de temas (ThemeTokens por slug)."""

from __future__ import annotations

from app.domain.models import ThemeTokens

THEMES_BUILTIN: dict[str, ThemeTokens] = {
    "ads-juicy-fresh": ThemeTokens(
        bg_color='#0d0c15',
        title_color='#ffffff',
        text_color='#ffffff',
        icon_color='#6562af',
        border_color='#e4e2e2',
        accent_color='#81ff00',
    ),
    "algolia": ThemeTokens(
        bg_color='#050f2c',
        title_color='#2dde98',
        text_color='#00aeff',
        icon_color='#ffffff',
        border_color='#e4e2e2',
        accent_color='#00aeff',
    ),
    "ambient-gradient": ThemeTokens(
        bg_color='#4158d0',
        title_color='#ffffff',
        text_color='#ffffff',
        icon_color='#ffffff',
        border_color='#ae58a1',
        accent_color='#ffffff',
    ),
    "android-dark": ThemeTokens(
        bg_color='#000000',
        title_color='#3ddc84',
        text_color='#3ddc84',
        icon_color='#3ddc84',
        border_color='#3ddc84',
        accent_color='#3ddc84',
    ),
    "apprentice": ThemeTokens(
        bg_color='#262626',
        title_color='#ffffaf',
        text_color='#ffffff',
        icon_color='#bcbcbc',
        border_color='#e4e2e2',
        accent_color='#ffffff',
    ),
    "aura": ThemeTokens(
        bg_color='#15141b',
        title_color='#ffca85',
        text_color='#a277ff',
        icon_color='#61ffca',
        border_color='#e4e2e2',
        accent_color='#a277ff',
    ),
    "aura-dark": ThemeTokens(
        bg_color='#252334',
        title_color='#6cffd0',
        text_color='#ff7372',
        icon_color='#dbdbdb',
        border_color='#e4e2e2',
        accent_color='#ff7372',
    ),
    "ayu-light": ThemeTokens(
        bg_color='#fafafa',
        title_color='#f07171',
        text_color='#55b4d4',
        icon_color='#575f66',
        border_color='#f0f0f0',
        accent_color='#ff9940',
    ),
    "ayu-mirage": ThemeTokens(
        bg_color='#1f2430',
        title_color='#73d0ff',
        text_color='#f4cd7c',
        icon_color='#c7c8c2',
        border_color='#e4e2e2',
        accent_color='#f4cd7c',
    ),
    "bear": ThemeTokens(
        bg_color='#1f2023',
        title_color='#00aeff',
        text_color='#e03c8a',
        icon_color='#bcb28d',
        border_color='#e4e2e2',
        accent_color='#e03c8a',
    ),
    "black-ice": ThemeTokens(
        bg_color='#151515',
        title_color='#ffffff',
        text_color='#ffffff',
        icon_color='#9f9f9f',
        border_color='#e4e2e2',
        accent_color='#00e7ff',
    ),
    "blood": ThemeTokens(
        bg_color='#ffffff',
        title_color='#ff5f5f',
        text_color='#ff5f5f',
        icon_color='#273849',
        border_color='#a8a8a8',
        accent_color='#ff5f5f',
    ),
    "blood-dark": ThemeTokens(
        bg_color='#142b37',
        title_color='#ff5f5f',
        text_color='#ff5f5f',
        icon_color='#ffffff',
        border_color='#e4e2e2',
        accent_color='#ff5f5f',
    ),
    "blue-green": ThemeTokens(
        bg_color='#040f0f',
        title_color='#f5b700',
        text_color='#2f97c1',
        icon_color='#0cf574',
        border_color='#e4e2e2',
        accent_color='#2f97c1',
    ),
    "blue-navy": ThemeTokens(
        bg_color='#000000',
        title_color='#82aaff',
        text_color='#82aaff',
        icon_color='#82aaff',
        border_color='#ffffff',
        accent_color='#82aaff',
    ),
    "blueberry": ThemeTokens(
        bg_color='#242938',
        title_color='#89ddff',
        text_color='#82aaff',
        icon_color='#27e8a7',
        border_color='#e4e2e2',
        accent_color='#82aaff',
    ),
    "blueberry-duo": ThemeTokens(
        bg_color='#0d1117',
        title_color='#89ddff',
        text_color='#82aaff',
        icon_color='#27e8a7',
        border_color='#e4e2e2',
        accent_color='#82aaff',
    ),
    "blux": ThemeTokens(
        bg_color='#263d46',
        title_color='#28ecfa',
        text_color='#0f80aa',
        icon_color='#ffffff',
        border_color='#e4e2e2',
        accent_color='#018596',
    ),
    "buefy": ThemeTokens(
        bg_color='#ffffff',
        title_color='#ff3860',
        text_color='#7957d5',
        icon_color='#363636',
        border_color='#a8a8a8',
        accent_color='#7957d5',
    ),
    "buefy-dark": ThemeTokens(
        bg_color='#1a1b27',
        title_color='#ff3860',
        text_color='#7957d5',
        icon_color='#ababab',
        border_color='#e4e2e2',
        accent_color='#7957d5',
    ),
    "burnt-neon": ThemeTokens(
        bg_color='#0d1117',
        title_color='#ff6906',
        text_color='#ff6906',
        icon_color='#c6ab07',
        border_color='#98989a',
        accent_color='#fe25b1',
    ),
    "calm": ThemeTokens(
        bg_color='#373f51',
        title_color='#edae49',
        text_color='#e07a5f',
        icon_color='#ebcfb2',
        border_color='#e4e2e2',
        accent_color='#e07a5f',
    ),
    "calm-pink": ThemeTokens(
        bg_color='#2b2d40',
        title_color='#ebcfb2',
        text_color='#e07a5f',
        icon_color='#e1bc29',
        border_color='#e1bc29',
        accent_color='#e07a5f',
    ),
    "carbonfox": ThemeTokens(
        bg_color='#161616',
        title_color='#78a9ff',
        text_color='#dfdfe0',
        icon_color='#08bdba',
        border_color='#282828',
        accent_color='#25be6a',
    ),
    "catppuccin-frappe": ThemeTokens(
        bg_color='#303446',
        title_color='#ca9ee6',
        text_color='#c6d0f5',
        icon_color='#b5bfe2',
        border_color='#e4e2e2',
        accent_color='#81c8be',
    ),
    "catppuccin-latte": ThemeTokens(
        bg_color='#eff1f5',
        title_color='#8839ef',
        text_color='#4c4f69',
        icon_color='#5c5f77',
        border_color='#e4e2e2',
        accent_color='#179299',
    ),
    "catppuccin-macchiato": ThemeTokens(
        bg_color='#24273a',
        title_color='#c6a0f6',
        text_color='#cad3f5',
        icon_color='#b8c0e0',
        border_color='#e4e2e2',
        accent_color='#8bd5ca',
    ),
    "catppuccin-mocha": ThemeTokens(
        bg_color='#1e1e2e',
        title_color='#cba6f7',
        text_color='#cdd6f4',
        icon_color='#bac2de',
        border_color='#e4e2e2',
        accent_color='#94e2d5',
    ),
    "chartreuse-dark": ThemeTokens(
        bg_color='#000000',
        title_color='#00aeff',
        text_color='#7fff00',
        icon_color='#ffffff',
        border_color='#e4e2e2',
        accent_color='#7fff00',
    ),
    "city-lights": ThemeTokens(
        bg_color='#1d252c',
        title_color='#5d8cb3',
        text_color='#5d8cb3',
        icon_color='#5d8cb3',
        border_color='#1d252c',
        accent_color='#718ca1',
    ),
    "cobalt": ThemeTokens(
        bg_color='#0d1117',
        title_color='#0480ef',
        text_color='#e683d9',
        icon_color='#75eeb2',
        border_color='#e4e2e2',
        accent_color='#e683d9',
    ),
    "cobalt2": ThemeTokens(
        bg_color='#193549',
        title_color='#ffffff',
        text_color='#ffc600',
        icon_color='#0088ff',
        border_color='#e4e2e2',
        accent_color='#ffc600',
    ),
    "codestackr": ThemeTokens(
        bg_color='#09131b',
        title_color='#ffe400',
        text_color='#ff652f',
        icon_color='#ffffff',
        border_color='#e4e2e2',
        accent_color='#ff652f',
    ),
    "cyber-streakglow": ThemeTokens(
        bg_color='#e20feb',
        title_color='#ebebeb',
        text_color='#64e8eb',
        icon_color='#ebebeb',
        border_color='#00ebe1',
        accent_color='#5aeb59',
    ),
    "darcula": ThemeTokens(
        bg_color='#242424',
        title_color='#84628f',
        text_color='#ba5f17',
        icon_color='#bebebe',
        border_color='#e4e2e2',
        accent_color='#ba5f17',
    ),
    "dark": ThemeTokens(
        bg_color='#151515',
        title_color='#fefefe',
        text_color='#fefefe',
        icon_color='#9e9e9e',
        border_color='#e4e2e2',
        accent_color='#fb8c00',
    ),
    "dark-aura": ThemeTokens(
        bg_color='#760a11',
        title_color='#eb5454',
        text_color='#ff8f62',
        icon_color='#eb5454',
        border_color='#310c69',
        accent_color='#c1184e',
    ),
    "dark-minimalist": ThemeTokens(
        bg_color='#211f27',
        title_color='#89b4fa',
        text_color='#e5e5e5',
        icon_color='#d0d1d3',
        border_color='#b9b9c0',
        accent_color='#d484f4',
    ),
    "dark-smoky": ThemeTokens(
        bg_color='#0b0c10',
        title_color='#66fcf1',
        text_color='#edf5e1',
        icon_color='#45a29e',
        border_color='#c5c6c7',
        accent_color='#edf5e1',
    ),
    "date-night": ThemeTokens(
        bg_color='#170f0c',
        title_color='#bb8470',
        text_color='#da7885',
        icon_color='#e1b2a2',
        border_color='#e4e2e2',
        accent_color='#da7885',
    ),
    "dawnfox": ThemeTokens(
        bg_color='#faf4ed',
        title_color='#286983',
        text_color='#575279',
        icon_color='#ea9d34',
        border_color='#e5e9f0',
        accent_color='#618774',
    ),
    "dayfox": ThemeTokens(
        bg_color='#f6f2ee',
        title_color='#2848a9',
        text_color='#352c24',
        icon_color='#ac5402',
        border_color='#f2e9e1',
        accent_color='#396847',
    ),
    "deepblue": ThemeTokens(
        bg_color='#165795',
        title_color='#639e29',
        text_color='#1add40',
        icon_color='#11e2e7',
        border_color='#ba9d6f',
        accent_color='#37dd57',
    ),
    "default": ThemeTokens(
        bg_color='#fffefe',
        title_color='#151515',
        text_color='#151515',
        icon_color='#464646',
        border_color='#e4e2e2',
        accent_color='#fb8c00',
    ),
    "deuteranopia-friendly-theme": ThemeTokens(
        bg_color='#000000',
        title_color='#56b4e9',
        text_color='#cc79a7',
        icon_color='#009e73',
        border_color='#e4e2e2',
        accent_color='#e69f00',
    ),
    "discord-old-blurple": ThemeTokens(
        bg_color='#2c2f33',
        title_color='#7289da',
        text_color='#7289da',
        icon_color='#ffffff',
        border_color='#e4e2e2',
        accent_color='#7289da',
    ),
    "dracula": ThemeTokens(
        bg_color='#282a36',
        title_color='#79dafa',
        text_color='#ff6e96',
        icon_color='#f8f8f2',
        border_color='#e4e2e2',
        accent_color='#ff6e96',
    ),
    "duskfox": ThemeTokens(
        bg_color='#232136',
        title_color='#569fba',
        text_color='#e0def4',
        icon_color='#f6c177',
        border_color='#393552',
        accent_color='#a3be8c',
    ),
    "earth": ThemeTokens(
        bg_color='#1e1615',
        title_color='#639e29',
        text_color='#c48519',
        icon_color='#ba9d6f',
        border_color='#ba9d6f',
        accent_color='#c48519',
    ),
    "elegant": ThemeTokens(
        bg_color='#03071e',
        title_color='#abcdef',
        text_color='#fedcba',
        icon_color='#ff7b00',
        border_color='#abcdef',
        accent_color='#ca6702',
    ),
    "everforest-dark": ThemeTokens(
        bg_color='#2d353b',
        title_color='#d3c6aa',
        text_color='#a7c080',
        icon_color='#9da9a0',
        border_color='#4f585e',
        accent_color='#a7c080',
    ),
    "everforest-light": ThemeTokens(
        bg_color='#f2f4ef',
        title_color='#55674e',
        text_color='#7f9c6f',
        icon_color='#8b9286',
        border_color='#c7ccc2',
        accent_color='#7f9c6f',
    ),
    "flag-india": ThemeTokens(
        bg_color='#ffffff',
        title_color='#250e62',
        text_color='#ff8f1c',
        icon_color='#509e2f',
        border_color='#e4e2e2',
        accent_color='#ff8f1c',
    ),
    "garden": ThemeTokens(
        bg_color='#094a4a',
        title_color='#d2dd3b',
        text_color='#6fdd6c',
        icon_color='#6fdd6c',
        border_color='#000000',
        accent_color='#d2dd3b',
    ),
    "git-dark": ThemeTokens(
        bg_color='#000000',
        title_color='#f05033',
        text_color='#f05033',
        icon_color='#f05033',
        border_color='#f05033',
        accent_color='#f05033',
    ),
    "github-dark": ThemeTokens(
        bg_color='#0d1117',
        title_color='#ffffff',
        text_color='#ffffff',
        icon_color='#39d353',
        border_color='#39d353',
        accent_color='#39d353',
    ),
    "github-dark-blue": ThemeTokens(
        bg_color='#0d1117',
        title_color='#fefefe',
        text_color='#fefefe',
        icon_color='#9e9e9e',
        border_color='#e4e2e2',
        accent_color='#1f6feb',
    ),
    "github-dark-dimmed": ThemeTokens(
        bg_color='#24292f',
        title_color='#adbac7',
        text_color='#539bf5',
        icon_color='#adbac7',
        border_color='#373e47',
        accent_color='#539bf5',
    ),
    "github-green-purple": ThemeTokens(
        bg_color='#000000',
        title_color='#800080',
        text_color='#7fff00',
        icon_color='#ffffff',
        border_color='#000000',
        accent_color='#7fff00',
    ),
    "github-light": ThemeTokens(
        bg_color='#ffffff',
        title_color='#39d353',
        text_color='#24292f',
        icon_color='#1f6feb',
        border_color='#39d353',
        accent_color='#39d353',
    ),
    "gotham": ThemeTokens(
        bg_color='#0c1014',
        title_color='#599cab',
        text_color='#2aa889',
        icon_color='#99d1ce',
        border_color='#e4e2e2',
        accent_color='#2aa889',
    ),
    "graywhite": ThemeTokens(
        bg_color='#ffffff',
        title_color='#24292e',
        text_color='#24292e',
        icon_color='#24292e',
        border_color='#ababab',
        accent_color='#24292e',
    ),
    "great-gatsby": ThemeTokens(
        bg_color='#000000',
        title_color='#ffb74d',
        text_color='#ffa726',
        icon_color='#ffd95b',
        border_color='#e4e2e2',
        accent_color='#ffa726',
    ),
    "green-nur": ThemeTokens(
        bg_color='#0a1e17',
        title_color='#5affc8',
        text_color='#5affc8',
        icon_color='#ffffff',
        border_color='#e4e2e2',
        accent_color='#5affc8',
    ),
    "gruvbox": ThemeTokens(
        bg_color='#282828',
        title_color='#fe8019',
        text_color='#fabd2f',
        icon_color='#8ec07c',
        border_color='#e4e2e2',
        accent_color='#fabd2f',
    ),
    "gruvbox-duo": ThemeTokens(
        bg_color='#0d1117',
        title_color='#fe8019',
        text_color='#fabd2f',
        icon_color='#8ec07c',
        border_color='#a8a8a8',
        accent_color='#fabd2f',
    ),
    "gruvbox-light": ThemeTokens(
        bg_color='#fbf1c7',
        title_color='#af3a03',
        text_color='#b57614',
        icon_color='#427b58',
        border_color='#e4e2e2',
        accent_color='#b57614',
    ),
    "hacker": ThemeTokens(
        bg_color='#000000',
        title_color='#20c20e',
        text_color='#20c20e',
        icon_color='#20c20e',
        border_color='#20c20e',
        accent_color='#20c20e',
    ),
    "hacker-inverted": ThemeTokens(
        bg_color='#20c20e',
        title_color='#000000',
        text_color='#000000',
        icon_color='#000000',
        border_color='#000000',
        accent_color='#000000',
    ),
    "halloween": ThemeTokens(
        bg_color='#1c1a2b',
        title_color='#ffc400',
        text_color='#fb9600',
        icon_color='#ffc400',
        border_color='#ffc400',
        accent_color='#fdef49',
    ),
    "highcontrast": ThemeTokens(
        bg_color='#000000',
        title_color='#ffffff',
        text_color='#ffffff',
        icon_color='#c5c5c5',
        border_color='#bebebe',
        accent_color='#fb8c00',
    ),
    "holi-theme": ThemeTokens(
        bg_color='#030314',
        title_color='#5fabee',
        text_color='#d6e7ff',
        icon_color='#85a4c0',
        border_color='#85a4c0',
        accent_color='#d6e7ff',
    ),
    "horizon": ThemeTokens(
        bg_color='#1c1e26',
        title_color='#59e1e3',
        text_color='#23bd87',
        icon_color='#fab795',
        border_color='#1c1e26',
        accent_color='#e95678',
    ),
    "humoris": ThemeTokens(
        bg_color='#dfaf77',
        title_color='#191419',
        text_color='#393c3c',
        icon_color='#444444',
        border_color='#e8e6e4',
        accent_color='#683c2c',
    ),
    "iceberg": ThemeTokens(
        bg_color='#1e2132',
        title_color='#d2d4de',
        text_color='#d2d4de',
        icon_color='#327698',
        border_color='#33374c',
        accent_color='#84a0c6',
    ),
    "icegray": ThemeTokens(
        bg_color='#ffffff',
        title_color='#3c3c3c',
        text_color='#515151',
        icon_color='#636363',
        border_color='#515151',
        accent_color='#686868',
    ),
    "java-dark": ThemeTokens(
        bg_color='#000000',
        title_color='#5382a1',
        text_color='#f89820',
        icon_color='#5382a1',
        border_color='#f89820',
        accent_color='#f89820',
    ),
    "javascript": ThemeTokens(
        bg_color='#f7df1e',
        title_color='#000000',
        text_color='#000000',
        icon_color='#000000',
        border_color='#000000',
        accent_color='#000000',
    ),
    "javascript-dark": ThemeTokens(
        bg_color='#000000',
        title_color='#ffffff',
        text_color='#f7df1e',
        icon_color='#f7df1e',
        border_color='#f7df1e',
        accent_color='#f7df1e',
    ),
    "jolly": ThemeTokens(
        bg_color='#291b3e',
        title_color='#a960ff',
        text_color='#ff64da',
        icon_color='#ffffff',
        border_color='#e4e2e2',
        accent_color='#ff64da',
    ),
    "kacho-ga": ThemeTokens(
        bg_color='#402b23',
        title_color='#a64833',
        text_color='#bf4a3f',
        icon_color='#d9c8a9',
        border_color='#e4e2e2',
        accent_color='#bf4a3f',
    ),
    "kanagawa-paper": ThemeTokens(
        bg_color='#1f1f28',
        title_color='#98bb6c',
        text_color='#7aa89f',
        icon_color='#c4b28a',
        border_color='#54546d',
        accent_color='#7fb4ca',
    ),
    "leafy": ThemeTokens(
        bg_color='#081c15',
        title_color='#ff5400',
        text_color='#abcabc',
        icon_color='#fecfec',
        border_color='#abcdef',
        accent_color='#abcdef',
    ),
    "maroongold": ThemeTokens(
        bg_color='#260000',
        title_color='#f7ef8a',
        text_color='#f7ef8a',
        icon_color='#e0aa3e',
        border_color='#e4e2e2',
        accent_color='#f7ef8a',
    ),
    "material": ThemeTokens(
        bg_color='#263238',
        title_color='#ffab91',
        text_color='#80cbc4',
        icon_color='#b0bec5',
        border_color='#e4e2e2',
        accent_color='#80cbc4',
    ),
    "material-palenight": ThemeTokens(
        bg_color='#292d3e',
        title_color='#89ddff',
        text_color='#c792ea',
        icon_color='#a6accd',
        border_color='#e4e2e2',
        accent_color='#c792ea',
    ),
    "merko": ThemeTokens(
        bg_color='#0a0f0b',
        title_color='#b7d364',
        text_color='#abd200',
        icon_color='#68b587',
        border_color='#e4e2e2',
        accent_color='#abd200',
    ),
    "meta-dark": ThemeTokens(
        bg_color='#1c2b33',
        title_color='#ffffff',
        text_color='#ffffff',
        icon_color='#ffffff',
        border_color='#ffffff',
        accent_color='#0081fb',
    ),
    "meta-light": ThemeTokens(
        bg_color='#ffffff',
        title_color='#1c2b33',
        text_color='#1c2b33',
        icon_color='#1c2b33',
        border_color='#1c2b33',
        accent_color='#0081fb',
    ),
    "microsoft": ThemeTokens(
        bg_color='#ffffff',
        title_color='#00a4ef',
        text_color='#ffb900',
        icon_color='#7fba00',
        border_color='#737373',
        accent_color='#7fba00',
    ),
    "microsoft-dark": ThemeTokens(
        bg_color='#000000',
        title_color='#00a4ef',
        text_color='#ffb900',
        icon_color='#7fba00',
        border_color='#737373',
        accent_color='#7fba00',
    ),
    "midnight-purple": ThemeTokens(
        bg_color='#000000',
        title_color='#9f4bff',
        text_color='#9745f5',
        icon_color='#ffffff',
        border_color='#e4e2e2',
        accent_color='#9745f5',
    ),
    "modern-lilac": ThemeTokens(
        bg_color='#0a0e12',
        title_color='#fab795',
        text_color='#c770f0',
        icon_color='#fab795',
        border_color='#1c1e26',
        accent_color='#5d417a',
    ),
    "modern-lilac2": ThemeTokens(
        bg_color='#0a0e12',
        title_color='#ffffff',
        text_color='#c770f0',
        icon_color='#ffffff',
        border_color='#1c1e26',
        accent_color='#5d417a',
    ),
    "moltack": ThemeTokens(
        bg_color='#f5e1c0',
        title_color='#86092c',
        text_color='#86092c',
        icon_color='#574038',
        border_color='#e4e2e2',
        accent_color='#86092c',
    ),
    "monokai": ThemeTokens(
        bg_color='#272822',
        title_color='#e28905',
        text_color='#eb1f6a',
        icon_color='#f1f1eb',
        border_color='#e4e2e2',
        accent_color='#eb1f6a',
    ),
    "monokai-metallian": ThemeTokens(
        bg_color='#1f222e',
        title_color='#f8d866',
        text_color='#f85d7f',
        icon_color='#9ca2b8',
        border_color='#ffffff',
        accent_color='#fc9867',
    ),
    "navy-gear": ThemeTokens(
        bg_color='#000021',
        title_color='#c3dd00',
        text_color='#c3dd00',
        icon_color='#1fa0dd',
        border_color='#ffffff',
        accent_color='#1fa0dd',
    ),
    "neon": ThemeTokens(
        bg_color='#000000',
        title_color='#ff449f',
        text_color='#00ead3',
        icon_color='#fff5b7',
        border_color='#ffffff',
        accent_color='#00ead3',
    ),
    "neon-blurange": ThemeTokens(
        bg_color='#030d6b',
        title_color='#25fb88',
        text_color='#25fb88',
        icon_color='#c7ccff',
        border_color='#c7ccff',
        accent_color='#fb750b',
    ),
    "neon-dark": ThemeTokens(
        bg_color='#020200',
        title_color='#f9dd3c',
        text_color='#5cadc0',
        icon_color='#ed7b25',
        border_color='#a8a8a8',
        accent_color='#e41d44',
    ),
    "neon-palenight": ThemeTokens(
        bg_color='#212237',
        title_color='#f9dd3c',
        text_color='#5cadc0',
        icon_color='#ed7b25',
        border_color='#a8a8a8',
        accent_color='#e41d44',
    ),
    "nightfox": ThemeTokens(
        bg_color='#192330',
        title_color='#719cd6',
        text_color='#dfdfe0',
        icon_color='#dbc074',
        border_color='#393b44',
        accent_color='#6c9581',
    ),
    "nightowl": ThemeTokens(
        bg_color='#011627',
        title_color='#ffeb95',
        text_color='#c792ea',
        icon_color='#7fdbca',
        border_color='#e4e2e2',
        accent_color='#c792ea',
    ),
    "noctis-minimus": ThemeTokens(
        bg_color='#1b2932',
        title_color='#72b7c0',
        text_color='#d3b692',
        icon_color='#c5cdd3',
        border_color='#f0f0f0',
        accent_color='#d3b692',
    ),
    "nord": ThemeTokens(
        bg_color='#2e3440',
        title_color='#88c0d0',
        text_color='#81a1c1',
        icon_color='#d8dee9',
        border_color='#e4e2e2',
        accent_color='#81a1c1',
    ),
    "nord-aurora": ThemeTokens(
        bg_color='#4c566a',
        title_color='#a3be8c',
        text_color='#d08770',
        icon_color='#88c0d0',
        border_color='#8fbcbb',
        accent_color='#a3be8c',
    ),
    "nordfox": ThemeTokens(
        bg_color='#2e3440',
        title_color='#81a1c1',
        text_color='#e5e9f0',
        icon_color='#ebcb8b',
        border_color='#3b4252',
        accent_color='#a3be8c',
    ),
    "ocean-dark": ThemeTokens(
        bg_color='#151a28',
        title_color='#ffffff',
        text_color='#8957b2',
        icon_color='#92d534',
        border_color='#e4e2e2',
        accent_color='#8957b2',
    ),
    "ocean-gradient": ThemeTokens(
        bg_color='#0093ea',
        title_color='#ffffff',
        text_color='#ffffff',
        icon_color='#ffffff',
        border_color='#000155',
        accent_color='#ffffff',
    ),
    "oceanic-next": ThemeTokens(
        bg_color='#1b2b34',
        title_color='#99c794',
        text_color='#5fb3b3',
        icon_color='#a7adba',
        border_color='#343d46',
        accent_color='#6699cc',
    ),
    "omni": ThemeTokens(
        bg_color='#191622',
        title_color='#e7de79',
        text_color='#ff79c6',
        icon_color='#e1e1e6',
        border_color='#e4e2e2',
        accent_color='#ff79c6',
    ),
    "one-dark-pro": ThemeTokens(
        bg_color='#23272e',
        title_color='#c678dd',
        text_color='#61afef',
        icon_color='#e5c06e',
        border_color='#e4e2e2',
        accent_color='#61afef',
    ),
    "onedark": ThemeTokens(
        bg_color='#282c34',
        title_color='#8eb573',
        text_color='#e4bf7a',
        icon_color='#df6d74',
        border_color='#e4e2e2',
        accent_color='#e4bf7a',
    ),
    "onedark-duo": ThemeTokens(
        bg_color='#0d1117',
        title_color='#8eb573',
        text_color='#e4bf7a',
        icon_color='#df6d74',
        border_color='#a8a8a8',
        accent_color='#e4bf7a',
    ),
    "outrun": ThemeTokens(
        bg_color='#141439',
        title_color='#ff1aff',
        text_color='#ffcc00',
        icon_color='#8080ff',
        border_color='#e4e2e2',
        accent_color='#ffcc00',
    ),
    "panda": ThemeTokens(
        bg_color='#31353a',
        title_color='#19f9d8',
        text_color='#19f9d8',
        icon_color='#ff75b5',
        border_color='#e4e2e2',
        accent_color='#19f9d8',
    ),
    "pastel": ThemeTokens(
        bg_color='#fff5f7',
        title_color='#be185d',
        text_color='#9d174d',
        icon_color='#ec4899',
        border_color='#fbcfe8',
        accent_color='#f472b6',
    ),
    "prussian": ThemeTokens(
        bg_color='#172f45',
        title_color='#38a0ff',
        text_color='#bddfff',
        icon_color='#6e93b5',
        border_color='#e4e2e2',
        accent_color='#bddfff',
    ),
    "python-dark": ThemeTokens(
        bg_color='#000000',
        title_color='#4b8bbe',
        text_color='#ffd43b',
        icon_color='#ffd43b',
        border_color='#4b8bbe',
        accent_color='#ffd43b',
    ),
    "radical": ThemeTokens(
        bg_color='#141321',
        title_color='#f8d847',
        text_color='#fe428e',
        icon_color='#a9fef7',
        border_color='#e4e2e2',
        accent_color='#fe428e',
    ),
    "react": ThemeTokens(
        bg_color='#20232a',
        title_color='#61dafb',
        text_color='#61dafb',
        icon_color='#ffffff',
        border_color='#e4e2e2',
        accent_color='#61dafb',
    ),
    "rising-sun": ThemeTokens(
        bg_color='#0c1116',
        title_color='#ffffff',
        text_color='#fff7ed',
        icon_color='#f6882b',
        border_color='#e4e3e3',
        accent_color='#f6882b',
    ),
    "rose": ThemeTokens(
        bg_color='#e9d8d4',
        title_color='#b71f36',
        text_color='#8d192b',
        icon_color='#862931',
        border_color='#e4e2e2',
        accent_color='#8d192b',
    ),
    "rose-pine": ThemeTokens(
        bg_color='#191724',
        title_color='#ebbcba',
        text_color='#9ccfd8',
        icon_color='#e0def4',
        border_color='#e4e2e2',
        accent_color='#9ccfd8',
    ),
    "rust-ferris-dark": ThemeTokens(
        bg_color='#000000',
        title_color='#f49600',
        text_color='#cc3a00',
        icon_color='#f66200',
        border_color='#ffffff',
        accent_color='#f49600',
    ),
    "rust-ferris-light": ThemeTokens(
        bg_color='#ffffff',
        title_color='#f49600',
        text_color='#cc3a00',
        icon_color='#f66200',
        border_color='#000000',
        accent_color='#f49600',
    ),
    "sakura-x": ThemeTokens(
        bg_color='#1a1b26',
        title_color='#ffffff',
        text_color='#e5c07b',
        icon_color='#c0caf5',
        border_color='#9d4edd',
        accent_color='#9d4edd',
    ),
    "sea": ThemeTokens(
        bg_color='#1565c0',
        title_color='#ffffff',
        text_color='#ffffff',
        icon_color='#ffffff',
        border_color='#ffffff',
        accent_color='#ffffff',
    ),
    "sea-dark": ThemeTokens(
        bg_color='#00c0ff',
        title_color='#000000',
        text_color='#000000',
        icon_color='#000000',
        border_color='#000000',
        accent_color='#000000',
    ),
    "shades-of-purple": ThemeTokens(
        bg_color='#2d2b55',
        title_color='#b362ff',
        text_color='#fad000',
        icon_color='#a599e9',
        border_color='#e4e2e2',
        accent_color='#fad000',
    ),
    "shadow-blue": ThemeTokens(
        bg_color='#0d1117',
        title_color='#3e6bff',
        text_color='#00779a',
        icon_color='#747474',
        border_color='#004490',
        accent_color='#004450',
    ),
    "shadow-brown": ThemeTokens(
        bg_color='#0d1117',
        title_color='#bb9863',
        text_color='#7d6642',
        icon_color='#747474',
        border_color='#31312d',
        accent_color='#31312d',
    ),
    "shadow-green": ThemeTokens(
        bg_color='#0d1117',
        title_color='#4db942',
        text_color='#007a00',
        icon_color='#747474',
        border_color='#003d00',
        accent_color='#003d00',
    ),
    "shadow-orange": ThemeTokens(
        bg_color='#0d1117',
        title_color='#ec861a',
        text_color='#bb5502',
        icon_color='#747474',
        border_color='#834400',
        accent_color='#834400',
    ),
    "shadow-purple": ThemeTokens(
        bg_color='#0d1117',
        title_color='#ca59ff',
        text_color='#6f42c1',
        icon_color='#747474',
        border_color='#570182',
        accent_color='#570182',
    ),
    "shadow-red": ThemeTokens(
        bg_color='#0d1117',
        title_color='#b94242',
        text_color='#9a0000',
        icon_color='#747474',
        border_color='#4f0000',
        accent_color='#4f0000',
    ),
    "slateorange": ThemeTokens(
        bg_color='#36393f',
        title_color='#faa627',
        text_color='#faa627',
        icon_color='#ffffff',
        border_color='#e4e2e2',
        accent_color='#faa627',
    ),
    "soft-green": ThemeTokens(
        bg_color='#222428',
        title_color='#00dc4d',
        text_color='#3ddc77',
        icon_color='#cecece',
        border_color='#e4e2e2',
        accent_color='#00dc4d',
    ),
    "solarized-dark": ThemeTokens(
        bg_color='#002b36',
        title_color='#b58900',
        text_color='#268bd2',
        icon_color='#859900',
        border_color='#e4e2e2',
        accent_color='#268bd2',
    ),
    "solarized-light": ThemeTokens(
        bg_color='#fdf6e3',
        title_color='#b58900',
        text_color='#268bd2',
        icon_color='#859900',
        border_color='#ababab',
        accent_color='#268bd2',
    ),
    "submarine-flowers": ThemeTokens(
        bg_color='#013e4e',
        title_color='#fff000',
        text_color='#ff8888',
        icon_color='#ff8650',
        border_color='#013e4e',
        accent_color='#ff8888',
    ),
    "sunset-gradient": ThemeTokens(
        bg_color='#8a2386',
        title_color='#ffffff',
        text_color='#ffffff',
        icon_color='#ffffff',
        border_color='#850000',
        accent_color='#fb8c00',
    ),
    "swift": ThemeTokens(
        bg_color='#f7f7f7',
        title_color='#f05237',
        text_color='#000000',
        icon_color='#000000',
        border_color='#e4e2e2',
        accent_color='#000000',
    ),
    "synthwave": ThemeTokens(
        bg_color='#2b213a',
        title_color='#ef8539',
        text_color='#e2e9ec',
        icon_color='#e5289e',
        border_color='#e4e2e2',
        accent_color='#e2e9ec',
    ),
    "taiga": ThemeTokens(
        bg_color='#031b1b',
        title_color='#1fbabe',
        text_color='#1fbabe',
        icon_color='#1f8f92',
        border_color='#062e2f',
        accent_color='#1f8f92',
    ),
    "telegram": ThemeTokens(
        bg_color='#ffffff',
        title_color='#179cde',
        text_color='#0088cc',
        icon_color='#0088cc',
        border_color='#333333',
        accent_color='#0088cc',
    ),
    "telegram-gradient": ThemeTokens(
        bg_color='#0088cc',
        title_color='#ffffff',
        text_color='#ffffff',
        icon_color='#ffffff',
        border_color='#ffffff',
        accent_color='#ffffff',
    ),
    "terafox": ThemeTokens(
        bg_color='#152528',
        title_color='#5a93aa',
        text_color='#ebebeb',
        icon_color='#fda47f',
        border_color='#2f3239',
        accent_color='#7aa4a1',
    ),
    "tokyonight": ThemeTokens(
        bg_color='#1a1b27',
        title_color='#bf91f3',
        text_color='#70a5fd',
        icon_color='#38bdae',
        border_color='#e4e2e2',
        accent_color='#70a5fd',
    ),
    "tokyonight-duo": ThemeTokens(
        bg_color='#0d1117',
        title_color='#bf91f3',
        text_color='#70a5fd',
        icon_color='#38bdae',
        border_color='#a8a8a8',
        accent_color='#70a5fd',
    ),
    "transparent": ThemeTokens(
        bg_color='#0d1117',
        title_color='#0579c3',
        text_color='#006aff',
        icon_color='#417e87',
        border_color='#e4e2e2',
        accent_color='#006aff',
    ),
    "travelers-theme": ThemeTokens(
        bg_color='#150e1f',
        title_color='#f2f2f2',
        text_color='#f2f2f2',
        icon_color='#f2f2f2',
        border_color='#e4e2e2',
        accent_color='#f28157',
    ),
    "violet-dark": ThemeTokens(
        bg_color='#000000',
        title_color='#ff0089',
        text_color='#ff0089',
        icon_color='#ff0089',
        border_color='#ff0089',
        accent_color='#ff0089',
    ),
    "violet-punch": ThemeTokens(
        bg_color='#000000',
        title_color='#cb0b45',
        text_color='#afb5dd',
        icon_color='#dddddd',
        border_color='#e4e2e2',
        accent_color='#3934dd',
    ),
    "vision-friendly-dark": ThemeTokens(
        bg_color='#000000',
        title_color='#785ef0',
        text_color='#ffb000',
        icon_color='#ffffff',
        border_color='#e4e2e2',
        accent_color='#ffb000',
    ),
    "vitesse": ThemeTokens(
        bg_color='#000000',
        title_color='#b8a965',
        text_color='#80a665',
        icon_color='#bd976a',
        border_color='#4d9375',
        accent_color='#4d9375',
    ),
    "vue": ThemeTokens(
        bg_color='#fffefe',
        title_color='#41b883',
        text_color='#41b883',
        icon_color='#273849',
        border_color='#a8a8a8',
        accent_color='#41b883',
    ),
    "vue-dark": ThemeTokens(
        bg_color='#273849',
        title_color='#41b883',
        text_color='#41b883',
        icon_color='#fffefe',
        border_color='#e4e2e2',
        accent_color='#41b883',
    ),
    "whatsapp-dark": ThemeTokens(
        bg_color='#121b22',
        title_color='#00a884',
        text_color='#e3e7ea',
        icon_color='#888d90',
        border_color='#1b2832',
        accent_color='#273741',
    ),
    "whatsapp-dark2": ThemeTokens(
        bg_color='#0b141b',
        title_color='#21c063',
        text_color='#f7f8fa',
        icon_color='#858a8d',
        border_color='#103629',
        accent_color='#858a8d',
    ),
    "whatsapp-light": ThemeTokens(
        bg_color='#ffffff',
        title_color='#16d351',
        text_color='#121b22',
        icon_color='#73828a',
        border_color='#e4e2e2',
        accent_color='#008069',
    ),
    "whatsapp-light2": ThemeTokens(
        bg_color='#ffffff',
        title_color='#1dab61',
        text_color='#131a20',
        icon_color='#767b7d',
        border_color='#d8fdd2',
        accent_color='#767b7d',
    ),
    "windows-dark": ThemeTokens(
        bg_color='#000000',
        title_color='#00a4ef',
        text_color='#00a4ef',
        icon_color='#00a4ef',
        border_color='#00a4ef',
        accent_color='#00a4ef',
    ),
    "yeblu": ThemeTokens(
        bg_color='#002046',
        title_color='#ffff00',
        text_color='#ffff00',
        icon_color='#ffffff',
        border_color='#e4e2e2',
        accent_color='#ffff00',
    ),
    "yellowdark": ThemeTokens(
        bg_color='#000000',
        title_color='#ffef00',
        text_color='#ffef00',
        icon_color='#a5a5a5',
        border_color='#000000',
        accent_color='#ffef00',
    ),
    "youtube-dark": ThemeTokens(
        bg_color='#0f0f0f',
        title_color='#ff0000',
        text_color='#ffffff',
        icon_color='#bcbcbc',
        border_color='#272727',
        accent_color='#ffffff',
    ),
}
